default_stages:
  - commit
exclude: ^docs/conf.py
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-xml
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - "--fix=auto"
  - repo: "https://github.com/hadialqattan/pycln"
    rev: v2.1.3
    hooks:
      - id: pycln
        exclude: ^docs/conf.py
  - repo: "https://github.com/asottile/pyupgrade"
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: ^docs/conf.py
        args:
          - "--py39-plus"
  - repo: https://github.com/myint/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        exclude: &fixtures docs/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: *fixtures
        args: [--py39-plus]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        exclude: *fixtures
        args: ["--split-summary-body", "--max-summary-lines=2"]
        files: src
  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: *fixtures
  - repo: "https://github.com/ambv/black"
    rev: 23.3.0
    hooks:
      - id: black
        exclude: *fixtures
  - repo: "https://github.com/pycqa/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: *fixtures
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        args: [--fix]
