class Config:
    LINKS = {
        "wow-client.zip": "https://duskhavenfiles.dev/WoW%203.3.5.zip",
        "wow.exe": "https://duskhavenfiles.dev/wow.exe",
        "Data/patch-5.MPQ": "https://duskhavenfiles.dev/patch-5.mpq",
        "Data/patch-A.MPQ": "https://duskhavenfiles.dev/patch-A.MPQ",
        "Data/patch-Z.mpq": "https://duskhavenfiles.dev/patch-Z.mpq",
    }

    WOW_WTF_CONFIG = {
        "locale": "enUS",
        "hwDetect": "0",
        "gxRefresh": "60",
        "gxMultisampleQuality": "0.000000",
        "gxFixLag": "0",
        "videoOptionsVersion": "3",
        "movie": "0",
        "Gamma": "1.000000",
        "readEULA": "1",
        "showToolsUI": "1",
        "Sound_OutputDriverName": "System Default",
        "Sound_MusicVolume": "0.10000000149012",
        "Sound_AmbienceVolume": "0.10000000149012",
        "farclip": "727",
        "specular": "1",
        "groundEffectDensity": "24",
        "projectedTextures": "1",
        "realmlist": "logon.duskhaven.net",
        "patchlist": "ignore",
        "gxWindow": "1",
        "gxMaximize": "1",
        "readTOS": "1",
        "mouseSpeed": "1",
        "gxResolution": "1920x1080",
        "readTerminationWithoutNotice": "1",
        "accounttype": "LK",
        "realmName": "Smolderthorn (Vanilla+)",
        "Sound_MasterVolume": "0.10000000149012",
        "gameTip": "125",
        "lastCharacterIndex": "1",
        "Sound_SFXVolume": "0.10000000149012",
        "checkAddonVersion": "0",
        "screenshotQuality": "10",
    }
