name: Create PySide6 exe with Nuitka-Action

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: "3.10"

      - name: Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libgl1 libegl1 libxkbcommon-dev fontconfig libglib2.0-0 libdbus-glib-1-2 \
          libfontconfig1-dev libfreetype6-dev \
          libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev \
          libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev \
          libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
          libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev \
          libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev \
          libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev \
          libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev \
          libopengl0 \
          python3-dev \
          python3-tk \
          patchelf
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka
          conda install libpython-static -y
      
      - name: Build Executable
        run: |
          python -m nuitka --standalone --enable-plugin=pyside6 --disable-console --onefile --include-data-dir=images=images --output-dir=build duskhaven_launcher.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
