name: WoW Duskhaven Launcher - Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          entry_point: main.py
          additional_args: "-F --windowed"

      - uses: actions/upload-artifact@v2
        with:
          name: duskhaven.launcher.exe
          path: src/dist/windows # or path/to/artifact
